name: Slice Intake
description: Define one Phase 1 slice that is ready for agent execution.
title: "slice: "
labels:
  - agent
body:
  - type: markdown
    attributes:
      value: |
        Use this form to define one bounded slice from `docs/DEVELOPMENT-SYSTEM.md`.
        Keep scope Phase 1 only.

  - type: textarea
    id: intent
    attributes:
      label: Intent
      description: One-sentence user outcome for this slice.
      placeholder: A founder can compose and decompose organisms from the systems view while boundary behavior is preserved.
    validations:
      required: true

  - type: dropdown
    id: lane
    attributes:
      label: Lane
      description: Choose exactly one operating lane.
      options:
        - core-integrity
        - experience
        - throughput
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Size
      description: S and M are preferred. Split L before starting.
      options:
        - S
        - M
        - L
    validations:
      required: true

  - type: textarea
    id: boundary
    attributes:
      label: Boundary
      description: Define in-scope and out-of-scope explicitly.
      placeholder: |
        In scope:
        - ...

        Out of scope:
        - ...
    validations:
      required: true

  - type: textarea
    id: touchpoints
    attributes:
      label: Touchpoints
      description: Call out the layer touchpoints for this slice.
      placeholder: |
        Kernel touchpoints:
        - ...

        API touchpoints:
        - ...

        Rendering touchpoints:
        - ...

        Content types affected:
        - ...
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks
      description: Risks, constraints, or faultlines to watch while implementing.
      placeholder: |
        - ...
        - ...
    validations:
      required: true

  - type: textarea
    id: acceptance_checks
    attributes:
      label: Acceptance Checks
      description: Copy and keep this checklist aligned with slice Definition Of Done.
      placeholder: |
        - [ ] User outcome is demonstrably true.
        - [ ] Domain rule behavior is implemented or explicitly unchanged.
        - [ ] Tests read like domain statements and cover changed behavior.
        - [ ] Rendering states are complete (loading/empty/error/auth-required) where applicable.
        - [ ] Unknown state handling is safe and legible.
        - [ ] `pnpm run check` passes.
        - [ ] Follow-up work is captured as new slices.
    validations:
      required: true

  - type: textarea
    id: verification
    attributes:
      label: Verification
      description: Automated and manual checks that prove completion.
      placeholder: |
        Automated verification:
        - pnpm run check

        Manual verification:
        - ...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Domain context, architecture boundaries, linked docs/files, and non-goals.
      placeholder: |
        Relevant docs/files:
        - docs/FOUNDATION.md
        - docs/ORGANISM-MODEL.md
        - ...

        Non-goals:
        - ...

  - type: textarea
    id: implementation_notes
    attributes:
      label: Implementation Notes
      description: Optional sequencing details.
      placeholder: Keep phase scope tight. No unrelated refactors.

  - type: markdown
    attributes:
      value: |
        After merge/completion, reflect outcomes in `docs/SLICE-TRACKER.md` and add `docs/decisions/NNN-title.md` if system shape changes.
